---
- name: Check if cgroups already enabled
  command: grep -q "cgroup_memory=1" /boot/firmware/cmdline.txt
  register: cgroups_check
  failed_when: false
  changed_when: false

- name: Enable cgroups for K3s
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: '^(.*rootwait.*)$'
    line: '\1 cgroup_memory=1 cgroup_enable=memory'
  when: cgroups_check.rc != 0
  notify: reboot
